export const SET_CLIENT = 'SET_CLIENT';
export const SET_APPLICANTS = 'SET_APPLICANTS';
export const RESET_NEW_APPLICANTS = 'RESET_NEW_APPLICANTS';
export const ADD_NEW_APPLICANT = 'ADD_NEW_APPLICANT';
export const DELETE_APPLICANT = 'DELETE_APPLICANT';
export const ADD_NEW_SELECTED_APPLICANT = 'ADD_NEW_SELECTED_APPLICANT';
export const DELETE_SELECETED_APPLICANT = 'DELETE_SELECETED_APPLICANT';
export const SET_RESULT = 'SET_RESULT';
